api/urls.py
from django.urls import path

from . import views

app_name = 'api'
urlpatterns = [
    path('todo/list/', views.ApiTodoLV.as_view(), name='list'),
    path('todo/<int:pk>/delete/', views.ApiTodoDelV.as_view(), name='delete'),
    path('todo/create/', views.ApiTodoCV.as_view(), name='create'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('todo/', include('todo.urls')),
    path('api/', include('api.urls')),
]

todo/urls.py
from django.urls import path
from . import views


app_name = 'todo'
urlpatterns = [
    path('', views.TodoTV.as_view(), name='index'),
]

api/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    name = models.CharField('Name', max_length=5, blank=True)
    todo = models.CharField('TODO', max_length=50)

    def __str__(self):
        return self.todo

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        if not self.name:
            self.name = '홍길동'
        super().save()

api/views.py
import json

from django.forms import model_to_dict
from django.http import JsonResponse
from django.shortcuts import render

# Create your views here.
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt, ensure_csrf_cookie
from django.views.generic.edit import BaseDeleteView, BaseCreateView
from django.views.generic.list import BaseListView

from todo.models import Todo


# csrf가 없으면 만들어서 반환하게 하도록 함
@method_decorator(ensure_csrf_cookie, name='dispatch')
class ApiTodoLV(BaseListView):
    model = Todo

    # def get(self, request, *args, **kwargs):
    #     tmpList = [
    #         {'id': 1, 'name': 'd김석훈', 'todo': 'Django 와 Vue.js 연동 프로그램을 만들고 있습니다.'},
    #         {'id': 2, 'name': 'd홍길동', 'todo': '이름을 안쓰면 홍길동으로 나와요...'},
    #         {'id': 3, 'name': 'd이순신', 'todo': '신에게는 아직 열두 척의 배가 있사옵니다.'},
    #         {'id': 4, 'name': 'd성춘향', 'todo': '그네 타기'},
    #     ]
    #     return JsonResponse(data=tmpList, safe=False)

    def render_to_response(self, context, **response_kwargs):
        todoList = list(context['object_list'].values())
        return JsonResponse(data=todoList, safe=False)

#csrf token 체크를 임시적으로 막아두기 위함
# @method_decorator(csrf_exempt, name='dispatch')
class ApiTodoDelV(BaseDeleteView):
    model = Todo

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return JsonResponse(data={}, status=204)

# @method_decorator(csrf_exempt, name='dispatch')
class ApiTodoCV(BaseCreateView):
    model = Todo
    fields = '__all__'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['data'] = json.loads(self.request.body)
        return kwargs

    def form_valid(self, form):
        print("form_valid()", form)
        self.object = form.save()
        newTodo = model_to_dict(self.object)
        print(f"newTodo: {newTodo}")
        return JsonResponse(data=newTodo, status=201)

    def form_invalid(self, form):
        print("form_invalid()", form)
        print("form_invalid()", self.request.POST)
        print("form_invalid()", self.request.body.decode('utf8'))
        return JsonResponse(data=form.errors, status=400)

mysite/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'home.html'

todo/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView


class TodoTV(TemplateView):
    template_name = 'todo/todo_index.html'

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}home.html{% endblock %}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/2fd93f26de.js" crossorigin="anonymous"></script>
    <link rel="icon" href="{% static 'img/favicon.ico' %}">

    {% block extra-style %}{% endblock %}

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todo:index' %}">Todo</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">Util</a>
            <ul class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
            </ul>
        </li>
      </ul>

      <form class="form-inline my-2">
          <input class="form-control mr-sm-2" type="search" placeholder="Search">
      </form>

      <ul class="navbar-nav ml-5 mr-5">
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fas fa-user"></i>&nbsp; Anonymous &nbsp;</a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'home' %}">Login</a></li>
            <li><a class="dropdown-item" href="{% url 'home' %}">Register</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
    {% block content %}{% endblock %}
</div>

{% block footer %}{% endblock %}

<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

{% block extra-script %}{% endblock %}

</body>
</html>

templates/home.html
{% extends 'base.html' %}
<h1>This is base.html</h1>

todo/templates/todo/todo_index.html
{% extends 'base.html' %}
{% block title %}Vue.js - Django todo app{% endblock %}

{% block extra-style %}
    <style>
        body {
            text-align: center;
            background-color: #ddd;
        }
        .inputBox {
            margin: auto;
            width: 70%;
            background: white;
            height: 50px;
            border-radius: 50px;
            line-height: 50px;
        }
        .inputBox .name {
            border-style: none;
            border-bottom: 1px solid #ddd;
            width: 90px;
            padding-left: 20px;
            line-height: 20px;
        }
        .inputBox .item {
            border-style: none;
            border-bottom: 1px solid #ddd;
            width: 400px;
            margin-left: 50px;
            padding-left: 20px;
            line-height: 20px;
        }
        .todoList {
            list-style: none;
            padding: 10px 0;
            text-align: left;
        }
        .todoList li {
            display: flex;
            height: 50px;
            line-height: 50px;
            margin: 0.5rem 0;
            padding: 0 0.9rem;
            background: white;
            border-radius: 5px;
        }
        .removeBtn {
            margin-left: auto;
            font-size: 20px;
        }
        .removeBtn:hover{
            color: red;
        }
    </style>
{% endblock %}

{% block content %}
<div id='app'>

    <h1>My Todo App !</h1>
    <strong>서로 할 일이나 의견을 공유해 봅시다.</strong>
    <br>

    # vue.js 내에서 요청을 보낼 것이므로 form이 아닌 DIV 태그를 사용한다.
    <div class="inputBox">
        <input class="name" type="text" placeholder="name ..." v-model.trim="name">
        <input class="item" type="text" placeholder="type anything welcomed ..." v-model.trim="todo"
            v-on:keyup.enter="add_todo()">
        <button class="btn btn-info btn-sm" v-on:click="add_todo()">ADD</button>
    </div>

    <ul class="todoList">
        <li v-for="(todo, index) in todoList">
            <span>[[ todo.name ]]:: [[ todo.todo ]]</span>
            <span class="removeBtn" v-on:click="remove_todo(todo, index)">x</span>
        </li>
    </ul>

</div>
{% endblock %}

{% block extra-script %}
<script src="https://unpkg.com/vue/dist/vue.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>
    axios.defaults.xsrfCookieName = 'csrftoken';
    axios.defaults.xsrfHeaderName = 'X-CSRFToken';

    var vm = new Vue({
        delimiters: ['[[', ']]'],
        el: '#app',
        data: {
            name: '',
            todo: '',
            todoList: [],
        },
        created: function(){
          console.log("created()...");
          this.fetch_all_todo();
        },
        methods: {
            fetch_all_todo: function(){
              console.log("fetch_all_todo()...");

              var vm = this;
              axios.get('/api/todo/list/')
                  .then(function(res){
                    console.log("GET RES", res);
                    vm.todoList = res.data;

                  })
                  .catch(function(err){
                    console.log("GET ERR", err)
                  })
            },
            add_todo: function(){
                console.log("add_todo()...");
                if (this.todo == '') return;
                if (this.name =='') this.name = '홍길동';

                var vm = this;
                var postData = {name: this.name, todo: this.todo};
                axios.post('/api/todo/create/', postData)
                    .then(function (res){
                      console.log("POST RES", res);
                      vm.todoList.push({id: res.data.id, name: res.data.name, todo: res.data.todo});
                    })
                    .catch(function(err){
                      console.log("POST ERR", err);
                    })

                this.name = this.todo = '';
            },
            remove_todo: function(todo, index){
                console.log("remove_todo()...", index);
                if (confirm("Really delete ?") == false) return;

                var vm = this;
                axios.delete('/api/todo/' + todo.id + '/delete/')
                    .then(function(res){
                      console.log("DELETE RES", res);
                      vm.todoList.splice(index, 1);
                    })
                    .catch(function(err){
                      console.log("DELETE ERR", err);
                    })



            },
        },
    })
</script>
{% endblock %}